### ISSUE TITLE
Remaining issues before 0.6.0

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/drawing#214]
### Pixbufs management

- [x] encapsulate the history management in a class
- [x] less slow history #200 
- [x] correct "reload" (without dialog, because undoable using the history) 
- [x] history memory leak (there was an actual issue here 10eca5426381255f9813a74d815a810e752a53a1 but otherwise concerning the current problem, i think the garbage collector just isn't very quick, or the system monitor is bad at reporting)
- ~~[ ] test scenarios where pixbufs are removed to save memory~~ abandoned (memory saving would need a new boolean attribute in the state dict)

### Classic tools

- [x] system fonts support for the text tool #251 #180 #58 

### Zoom

- [x] touch gesture #73 
- [x] better scroll-to-zoom method #183 
- [x] canvas tools' mouse signals ignore the zoom level #78 

### Selection and canvas tools

- [x] compatibility between the 3 selection tools 
  - abandon static attributes ~~no they're fine~~ no they're not, they break multi-tabs edition
  - [x] implement these features in the selection manager
  - [x] cropping or scaling break overlay coords when these tools change `_future_*` attributes
- [x] hidpi compatibility (#207, #236, ...) (huge issue but not a regression)
- [x] mouse cursor has unreliable coordinates.
  - [x] first with HiDPI of course...
  - [x] [scale/crop] when zoomed-in, the dead area is too big; when zoomed-out it's too small
  - [x] with selection, when cropping/scaling from the top/left
  - [x] with selection, when zoomed in/out
- wrong coords when...
  - [x] pasting with scroll/zoom #175 
  - [x] undoing/redoing a paste #223 
- ~~[ ] skew doesn't have mouse signals #21~~ skew isn't in the release notes so instead of fixing it i should...
- [x] hide the skew tool from the UI

### General

- [x] tests on:
  - gnome wayland
  - cinnamon
  - pantheon
  - smartphone-ish screen sizes
- [x] last translations update
- [x] version bump
- [x] appdata screenshots
- [x] help manual

----

## System

- Device (desktop computer/tablet/phone/...): any
- Desktop environment: any
- Package format (flatpak, native package, snap?): flatpak
- App version: 0.5.4 to 0.6.0

**Comment by maoschanz** [comment]
Hello @fitojb @xoan @moriel5 @shaqash @KAMI911 @pkomur @haurenburu @tim77, sorry to spam you all, but i'm about to (finally!) release the version 0.6 of this app.

I thought maybe you'd like to be informed in advance, so if you want to contribute again and if you have a little free time, you could update the translation you've contributed to:

| code | name             | completion |
|------|------------------|------------|
| es   | Castillan        | **79%**    |
| he   | Hebrew           | **47%**    |
| hu   | Hungarian        | **78%**    |
| pl   | Polish           | 89%        |
| pt_BR | Brazilian portuguese | **60%** |
| ru   | Russian          | **43%**    |

I don't know the actual date of the release (**there are probably still a few weeks left**), but at least the translatable strings will not change anymore until the next version.

If you have any question about a string to translate, don't hesitate to ask here!

----

@pan93412 @overflowcat your translations are pretty complete, but i mention you too because i've recently added support for Asian characters to the "text" tool, and it would be weird if this part of the release notes was the only one not translated in Chinese 😅

**Comment by maoschanz** [comment]
@frenchy82 pour le ppa je préviens à l'avance que les versions 0.6.0 et 0.6.1 ne seront pas compatibles avec bionic (pour la version 0.6.2 et plus, peut-être que si), si j'ai bien écrit mon truc la tentative de construction pour ces distros devrait échouer naturellement

**Comment by KAMI911** [comment]
I saw this now,

I will try to transate the remaining part of Hungarian.

Kami

Romain F. T. <notifications@github.com> ezt írta (időpont: 2020. szept.
17., Csü 10:04):
