### ISSUE TITLE
Ideas about tools (0.6.x to 0.8.0)

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/drawing#260]
# Classic tools

- Add a "number" tool or option (see #32) (that would be an optional one but why not)
  - [x] basic implementation **(0.6.1)**
  - [x] icon? **(0.6.1)**
  - [x] make it optional **(0.6.1)**
  - ~~[ ] cases with numbers bigger than the circle~~ no, no one cares
- [x] highlighter should support screenshots from "dark mode" websites **(0.6.2)**
- [x] ensure all tools are fully translatable (highlighter? points?) **(0.6.3)**
- [x] optional tool dedicated to the "dest_in/blur" operator #329 
- Arrows:
  - [x] Arrows with square end are broken **(0.6.3)**, now reported as #285 
  - [x] Arrows are ugly with some specific angles **(0.6.3)**, fixed by #286 
  - [x] Arrows are ugly with semi-transparency or specific cairo operators **(0.6.3)**
  - [x] Double-ended arrows #59 **(0.6.3)**
- [x] More dashes styles **(0.6.3)**
- [x] Remember anti-aliasing **(0.6.4)**
- Shape tool
  - [x] Remember the filling? (mentioned in #340 )
- ~~[ ] support for inserting RTL text #264~~ already fixed since 0.4.14
- Brushes
  - [x] dynamic width (proof of concept using speed)
  - [x] dynamic width (proof of concept using pressure)
  - [x] dynamic width (as an actual tool) **(0.8.0)**
  - [x] experimental airbrush 
  - [x] airbrush (as an actual tool) **(0.8.0)**
- Better painting tool
  - [x] "paint over entire image" option **(0.6.2)**
  - [x] improve whatever the "erase and replace" algo is doing **(0.6.4)** (using just a cairo path stroke as an outline)
  - ~~[ ] experiment sobel filter or something like that (looks hard but cool)~~

# Transform tools

- [x] actually rename everything "transform" instead of "canvas" **(0.6.1)**
- [x] fix stupid behaviour of rotate tool when the selection is flipped before being rotated **(0.6.1)**
- More filters? #308 
  - [x] "increase contrast" filter using blending modes **(0.8.0)**
  - [x] "emboss" filter using blending modes **(0.8.0)**
  - ~~[ ] https://en.wikipedia.org/wiki/Unsharp_masking~~ the notion of threshold makes it too complex for me

# Selection

- [x] sometimes coords jump when unselecting (details in #330 )
- [x] deletion leaving something else than transparency #232  **(0.8.0)**
- [x] not selecting the leaved color #232  **(0.8.0)**

**Comment by maoschanz** [comment]
to be continued in #369
