### ISSUE TITLE
Remaining issues before 0.8.0 release

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/drawing#330]
## Not entirely finished features

- [x] make a state pattern for the brush tool (related to #260 #116 )
  - [x] integrate the airbrush in it
  - [x] integrate the straight nips in it
    - ~~[ ] design icons for nib orientations~~ 0.8.1
  - [x] fix support for "erase" mode
  - [x] fix support for "source" mode
- [x] disable the blur mode 
  - [x] and add the censoring tool (#329 but it's not really in the release notes so it may be descoped)
- persist more tool options? 
  - [x] #346 refactoring
  - [x] text background #340 
  - [x] shape filling
- [x] better UX to present changes when new version #347

## Other minor problems

- [x] the "eraser" icon could look more like adwaita's 'edit-clear-all-symbolic'
- [x] jumps when the selection is defined by an "undo"
- ~~[ ] motion events on the minimap (#318 )~~ 0.8.1

## Releasing process

- [x] update the translations completion percentages
- [ ] gaphor diagrams
- [x] merge #319
  - [ ] and add tests
- [x] new screenshots
- [x] update the readme and the website text
