### ISSUE TITLE
Ideas about tools (0.8.0 to 1.0.0)

### ISSUE THREAD

**Issue by maoschanz** [maoschanz/drawing#369]
# Classic tools

- add shadow/outline to:
  - [x] line
  - [x] curve
  - [x] pencil
- Brushes:
  - [x] nib orientation
  - [x] icons for nib orientation
- [x] more rigid highlighter
- Text:
  - [x] 2 different kinds of outline (the current one is to thin in certain cases)
  - [x] anti-aliasing as an option
- [x] line orthogonal lock (#46 )

# Selection

- [x] define as image (#332 )
- [x] expand canvas to fit (#332)
- keys+mouse workflow (#46):
  - [x] alternative tools behaviours
  - [x] tooltips (#439)
  - ~~[ ] add to selection~~ descoped, #449 
  - ~~[ ] remove from selection~~ descoped, #449 
- ~~[ ]  invert selection (https://www.cairographics.org/cookbook/outside_clipping/ ??)~~, later reported as #442 (descoped)
- [x] restructure the menu-bar's "options" menu
- [x] adapt the thickness of the dashed ouline to the zoom level

# Transform tools

- [x] Cropping the selection more than possible, is possible
- [x] change the code that draws the preview to better use the entire window (scale, rotate, crop) #396 
- [x] automatically scroll further to the bottom-right when the user expands the canvas (crop, scale)
- cairo.Matrix transformation (skew) **[specific branch]**
  - [x] as a well implemented tool
  - [x] integration in selection menus
  - [x] with surface signals
  - [x] surface signals should use cursor tracking
  - [x] draw handles
  - [x] option: color of the new pixels (canvas only)
- [ ] Scale: option "pixels/percentage"?
- manage the optionsbar through a single .ui file **[specific branch]**
  - [x] this abstract code (ui only) manages: cancel, apply, help (all uris/tooltips are the same regardless of the transform tool), left-side menu 
  - the implementations have only the ui code for the centered widgets
    - [x] crop
    - [x] filters
    - [x] rotate
    - [x] scale
    - [x] skew
  - [x] the "options menu" has to be managed in python (boolean parameter? builder?)
- [x] incorrectly huge height after rotating a selection
- [x] adapt the thickness of the dashed ouline to the zoom level
